Refactor widgets and layer metadata
scverse/napari-spatialdata pull request #93
Opened 2023-05-23 15:31 UTC by melonora

This PR moves the widgets in interactive to a script specific for data widgets. On top of that it merges the code from @LucaMarconato regarding adding metadata to the layers with the current code on main. 

Utility functions have been moved to utils. Performance has been improved by submitting points and polygons data based on the maximum amount to be visualized, before performing any other calculations.

Also a bug has been fixed for the point data (x and y coordinates were not swapped, napari expects yx).

Closes #87 and #66, potentially closes #55

2023-05-26 09:07 UTC, melonora commented
@rahulbshrestha @tothmarcella Hi both, Could you please have a look at the tests that are failing and the code in general? It seems to be due to a missing attribute and a mismatch in dimensions in anndata.obs and blobs.shape. 

I think the changes are following what is intended so it could be that we have to change some tests.

2023-05-26 09:08 UTC, rahulbshrestha commented
Hi @melonora! Yup, I'll take a look.

2023-05-28 07:51 UTC, melonora commented
For the regionprops, we could also use dask regionprops. Would there be any objection to that?

2023-05-29 11:13 UTC, melonora commented on src/napari_spatialdata/_utils.py
> +    annotating_rows.obsm["region_radius"] = np.array([10.0] * len(merged_centroids))  # arbitrary value
This part is due to squidpy legacy code. Can this also be removed?

2023-05-30 12:12 UTC, giovp commented on src/napari_spatialdata/_utils.py
> +    from scanpy.plotting._utils import _set_colors_for_categorical_obs
this we copied over it frm scanpy so to not be dependent on scanpy anymore, it's in `categorical_utils.py`

2023-05-30 12:12 UTC, giovp commented on setup.cfg
> +    scanpy
remove scanpy  as requirement

2023-05-30 12:20 UTC, giovp requested changes
I would revert back to what we had before regarding passing annotation metadata to layers and to add layers. imho the spatialdata widget should be kept the same as we had before. @tothmarcella @rahulbshrestha could you also give it a comment here thanks!

2023-05-30 12:20 UTC, giovp commented on src/napari_spatialdata/_utils.py
> +def _find_annotation_for_labels(
it's unclear why this is needed, in the implementation from main there shouldn't be need for this. Is it possible that this is something you ported over from luca's branch and now it's here for legacy reason?

2023-05-30 12:20 UTC, giovp commented on src/napari_spatialdata/_interactive.py
> -        )
this part is replaced by the big/complex function below. I think this way to handle annotation metadata is much cleaner and would keep this.

2023-05-30 12:20 UTC, giovp commented on src/napari_spatialdata/_utils.py
> +def _find_annotation_for_shapes(
same here as before

2023-05-30 12:20 UTC, giovp commented on src/napari_spatialdata/_utils.py
> +def _find_annotation_for_regions(
same here

2023-05-30 12:20 UTC, giovp commented on src/napari_spatialdata/_utils.py
> +def _get_ellipses_from_circles(centroids: NDArrayA, radii: NDArrayA) -> NDArrayA:
same here

2023-06-04 15:44 UTC, LucaMarconato commented on src/napari_spatialdata/_sdata_widgets.py
> +            )
In `main` currently only ellipses are used, this is bad for performance and user experience, so definitely we should prefer always points to always shapes, I will make a PR. Re always points vs always shapes, I'll experiment a bit with small Visium datasets and get back to it.

2023-06-04 15:47 UTC, melonora commented on src/napari_spatialdata/_sdata_widgets.py
> +            )
Note that there is work ongoing in napari at the moment to actually fix this issue. Might already be included in 0.4.18 which is aimed for release next month

2023-06-04 15:58 UTC, LucaMarconato commented on src/napari_spatialdata/_sdata_widgets.py
> +            )
Very nice!

2023-06-17 06:41 UTC, melonora commented
Closing this in favor of new PR

2023-06-17 06:41 UTC, closed without merging